import onetimepad
m= "one time cipher"
print("msg to be encrypted is ",m)
cipher = onetimepad.encrypt(m, 'random')
print("Encrypted msg from sender is")
print(cipher)
print("plain text generated by receiver is")
msg = onetimepad.decrypt(cipher, 'random')
print(msg)
